import { loadGameplayPreferences, loadPlayerName } from './preferences.js';
import { createSoundPresentation } from './sound-presentation.js';
import { PROTOTYPE_SESSION_CONFIG } from '../core/session-config.js';
import { getMapDefinition } from '../core/world-config.js';
import { AssemblyPresentation } from '../render/assembly.js';
import { BaseDamagePresentation } from '../render/world-appearance.js';

// Controllers keep snapshots and dimensions on these live objects so session switches
// and resizing cannot leave a module holding an old value.
export function createAppState({ canvas = null, errorPanel = null, reducedNetworkMotion = { matches: false },
  preferences = loadGameplayPreferences(), playerName = loadPlayerName(), now = performance.now() } = {}) {
  const currentMap = getMapDefinition(PROTOTYPE_SESSION_CONFIG.mapId);
  return {
    viewport: {
      logicalWidth: 640,
      logicalHeight: 360,
      displayPixelScale: 1,
      renderScale: 1,
      HUD_TOP_HEIGHT: 23,
      hudBottomY: 329,
      camera: { ...currentMap.camera },
      cameraByMode: new Map(),
      zoomLevels: [1, 2, 3, 4, 5, 6, 8],
    },
    renderer: {
      canvas,
      errorPanel,
      gl: null,
      backgroundProgram: null,
      nebulaRenderer: null,
      enemyRenderer: null,
      shapes: null,
      bitmapText: null,
    },
    game: {
      sessions: new Map(),
      sessionMode: 'game',
      authority: null,
      session: null,
      sessionSnapshot: null,
      currentMap,
      gameRestorePending: false,
      gameHasEnteredGameplay: false,
      soloGameBundle: null,
      lastAutosaveAt: now,
      saveInFlight: false,
      saveQueued: false,
    },
    effects: {
      researchWave: null,
      networkPresentation: new Map(),
      baseDamage: new BaseDamagePresentation(),
      assembly: new AssemblyPresentation(),
      defeatSeenAt: null,
      reducedNetworkMotion,
      projectilePresentation: new Map(),
      impactBursts: [],
      attackFlashes: [],
      relayCollapse: null,
      RELAY_COLLAPSE_SECONDS: 2.2,
      perimeterIntel: [],
      perimeterIntelTick: -1,
    },
    // Audio and the part lab are presentation-only; main.js fills manager/forge at startup.
    audio: {
      manager: null,
      forge: null,
      ready: false,
      presentation: createSoundPresentation(),
    },
    partLab: null,
    openPartLab: null,
    ui: {
      devToolsOpen: false,
      partLabOpen: false,
      frontEndScreen: 'main',
      menuConfirm: null,
      escapeMenuPage: 'main',
      mapSelectOrigin: 'main',
      selectedRunMapId: PROTOTYPE_SESSION_CONFIG.mapId,
      dragging: false,
      pointer: { x: 320, y: 180 },
      lastPointerMotionAt: -Infinity,
      pointerDown: null,
      dragDistance: 0,
      placementArmed: false,
      bulkPlacementDefinitionId: null,
      buildCatalogOpen: false,
      buildCatalogPageId: 'core',
      selectedTowerId: null,
      towerActionPage: 0,
      towerActionPageTowerId: null,
      towerMenuMode: null,
      statusMessage: 'build live // no pause',
      statusUntil: 0,
      uiHitboxes: [],
      uiDrag: null,
      controlDrag: null,
      showAllRanges: false,
      showKps: true,
      showStatsPanel: false,
      testKeepSwarm: false,
      researchPage: 0,
      researchSelection: null,
      researchDetailPage: 0,
      reactorBuyCount: 1,
    },
    connection: {
      peerCoordinator: null,
      multiplayerClosing: false,
    },
    multiplayer: {
      role: null,
      phase: 'idle',
      roomCode: null,
      codeInput: '',
      status: 'peer link idle',
      detail: '',
      expiresAt: 0,
      playerName,
      editingName: false
    },
    social: {
      messages: [],
      presenceByPlayer: new Map(),
      presenceSequenceByPlayer: new Map(),
      pings: [],
      chatOpen: false,
      chatInput: '',
      rosterExpanded: false,
      pingArmed: false,
      lastPresenceSentAt: -Infinity,
      lastPresenceSignature: '',
      idleSent: true
    },
    timing: {
      frameTiming: { last: 0, average: 0, worst: 0 },
      telemetryByMode: new Map(),
      towerTelemetryByMode: new Map(),
      previousTime: now,
      fps: 0,
      frameCounter: 0,
      fpsWindow: now,
      lastGpuCheck: now,
    },
    preferences,
  };
}
