// Baked jfxr recipes for every built-in sound hook. The horde ships no audio files;
// these render at startup so every slot has an audible default until the part lab
// assigns a saved Signal Forge sound. Baked from the promoted part lab pack
// (2026-09-14) by scripts/bake-default-sounds.mjs; never edit by hand.
export const DEFAULT_SOUND_RECIPES = Object.freeze({
  fire: {"_version":1,"_name":"hit/hurt","_locked":[],"sampleRate":44100,"attack":0,"sustain":0,"sustainPunch":40,"decay":0.23,"tremoloDepth":0,"tremoloFrequency":2,"frequency":1610,"frequencySweep":-6100,"frequencyDeltaSweep":400,"repeatFrequency":0,"frequencyJump1Onset":60,"frequencyJump1Amount":-65,"frequencyJump2Onset":65,"frequencyJump2Amount":-10,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"whitenoise","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":19,"squareDuty":50,"squareDutySweep":0,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":18900,"lowPassCutoffSweep":7550,"highPassCutoff":0,"highPassCutoffSweep":15950,"compression":1.5,"normalization":true,"amplification":30},
  rocket_launch: {"_version":1,"_name":"hit/hurt","_locked":[],"sampleRate":44100,"attack":0.19,"sustain":0.18,"sustainPunch":40,"decay":1.01,"tremoloDepth":0,"tremoloFrequency":0,"frequency":2710,"frequencySweep":-6500,"frequencyDeltaSweep":-200,"repeatFrequency":0,"frequencyJump1Onset":65,"frequencyJump1Amount":-60,"frequencyJump2Onset":60,"frequencyJump2Amount":-10,"harmonics":0,"harmonicsFalloff":0.53,"waveform":"whitenoise","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":64,"squareDuty":45,"squareDutySweep":0,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":1,"lowPassCutoff":19900,"lowPassCutoffSweep":9600,"highPassCutoff":600,"highPassCutoffSweep":16900,"compression":1.5,"normalization":true,"amplification":30},
  laser: {"_version":1,"_name":"laser/shoot","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.07,"sustainPunch":80,"decay":0.03,"tremoloDepth":0,"tremoloFrequency":10,"frequency":800,"frequencySweep":-1200,"frequencyDeltaSweep":-600,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"whistle","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":80,"squareDuty":5,"squareDutySweep":90,"flangerOffset":8,"flangerOffsetSweep":-10,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":2,"normalization":true,"amplification":40},
  hit: {"_version":1,"_name":"horde/hitmarker soft","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.035,"sustainPunch":50,"decay":0.045,"tremoloDepth":24,"tremoloFrequency":176,"frequency":4010,"frequencySweep":-1000,"frequencyDeltaSweep":0,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":2,"harmonicsFalloff":0.4,"waveform":"whitenoise","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":50,"squareDutySweep":0,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":1,"bitCrushSweep":-16,"lowPassCutoff":5800,"lowPassCutoffSweep":-15550,"highPassCutoff":1500,"highPassCutoffSweep":-13450,"compression":1.6,"normalization":true,"amplification":30},
  explosion: {"_version":1,"_name":"explosion","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.1,"sustainPunch":80,"decay":0.41000000000000003,"tremoloDepth":0,"tremoloFrequency":10,"frequency":5910,"frequencySweep":-2100,"frequencyDeltaSweep":-1900,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"brownnoise","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":50,"squareDutySweep":0,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":2.2,"normalization":true,"amplification":60},
  control_apply: {"_version":1,"_name":"hit/hurt","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.03,"sustainPunch":20,"decay":0.09,"tremoloDepth":0,"tremoloFrequency":10,"frequency":810,"frequencySweep":-900,"frequencyDeltaSweep":-200,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"sawtooth","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":50,"squareDutySweep":0,"flangerOffset":3,"flangerOffsetSweep":-3,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":-10400,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":3.4,"normalization":true,"amplification":30},
  enemy_death: {"_version":1,"_name":"hit/hurt","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.03,"sustainPunch":0,"decay":0.09,"tremoloDepth":0,"tremoloFrequency":10,"frequency":600,"frequencySweep":-900,"frequencyDeltaSweep":-1000,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"tangent","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":50,"squareDutySweep":0,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":-13200,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":3.4,"normalization":true,"amplification":20},
  tower_placed: {"_version":1,"_name":"jump","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.08,"sustainPunch":0,"decay":0.41000000000000003,"tremoloDepth":0,"tremoloFrequency":10,"frequency":10,"frequencySweep":900,"frequencyDeltaSweep":0,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":10,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"breaker","interpolateNoise":false,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":25,"squareDutySweep":30,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":1,"lowPassCutoff":20800,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":1.8,"normalization":true,"amplification":30},
  tower_evolved: {"_version":1,"_name":"jump","_locked":[],"sampleRate":44100,"attack":0,"sustain":0,"sustainPunch":0,"decay":0.18,"tremoloDepth":0,"tremoloFrequency":10,"frequency":300,"frequencySweep":600,"frequencyDeltaSweep":100,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":10,"frequencyJump2Onset":65,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"breaker","interpolateNoise":false,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":25,"squareDutySweep":25,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":21000,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":1.7000000000000002,"normalization":true,"amplification":30},
  tower_sold: {"_version":1,"_name":"jump","_locked":[],"sampleRate":44100,"attack":0.01,"sustain":0.27,"sustainPunch":0,"decay":0.16,"tremoloDepth":0,"tremoloFrequency":33,"frequency":10,"frequencySweep":1500,"frequencyDeltaSweep":-100,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":70,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"brownnoise","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":25,"squareDutySweep":20,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":21300,"lowPassCutoffSweep":-400,"highPassCutoff":300,"highPassCutoffSweep":0,"compression":1.1,"normalization":true,"amplification":40},
  base_breached: {"_version":1,"_name":"hit/hurt","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.1,"sustainPunch":30,"decay":0.08,"tremoloDepth":0,"tremoloFrequency":10,"frequency":600,"frequencySweep":-700,"frequencyDeltaSweep":-800,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"tangent","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":50,"squareDutySweep":0,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":19800,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":1,"normalization":true,"amplification":50},
  run_started: {"_version":1,"_name":"laser/shoot","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.04,"sustainPunch":0,"decay":0.06,"tremoloDepth":0,"tremoloFrequency":10,"frequency":1500,"frequencySweep":-300,"frequencyDeltaSweep":-1200,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"square","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":35,"squareDutySweep":60,"flangerOffset":4,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":1,"normalization":true,"amplification":0},
  defeat: {"_version":1,"_name":"explosion","_locked":[],"sampleRate":44100,"attack":0,"sustain":1.39,"sustainPunch":90,"decay":1.74,"tremoloDepth":0,"tremoloFrequency":10,"frequency":7700,"frequencySweep":-2800,"frequencyDeltaSweep":-2500,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"pinknoise","interpolateNoise":false,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":50,"squareDutySweep":0,"flangerOffset":6,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":1,"normalization":true,"amplification":50},
  research_purchased: {"_version":1,"_name":"powerup","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.1,"sustainPunch":20,"decay":0.34,"tremoloDepth":0,"tremoloFrequency":10,"frequency":410,"frequencySweep":1900,"frequencyDeltaSweep":1400,"repeatFrequency":4.8,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"breaker","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":5,"squareDutySweep":-35,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":1.9,"normalization":true,"amplification":30},
  relay_completed: {"_version":1,"_name":"powerup","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.2,"sustainPunch":0,"decay":0.77,"tremoloDepth":0,"tremoloFrequency":10,"frequency":1010,"frequencySweep":1600,"frequencyDeltaSweep":900,"repeatFrequency":5.1,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"sawtooth","interpolateNoise":true,"vibratoDepth":570,"vibratoFrequency":764,"squareDuty":60,"squareDutySweep":-5,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":1.4,"normalization":true,"amplification":30},
  forge_income: {"_version":1,"_name":"pickup/coin","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.06,"sustainPunch":0,"decay":0.34,"tremoloDepth":0,"tremoloFrequency":10,"frequency":200,"frequencySweep":0,"frequencyDeltaSweep":0,"repeatFrequency":0,"frequencyJump1Onset":30,"frequencyJump1Amount":30,"frequencyJump2Onset":20,"frequencyJump2Amount":80,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"sine","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":35,"squareDutySweep":30,"flangerOffset":7,"flangerOffsetSweep":-3,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":2,"normalization":true,"amplification":20},
  ui_click: {"_version":1,"_name":"pickup/coin","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.06,"sustainPunch":0,"decay":0.34,"tremoloDepth":0,"tremoloFrequency":10,"frequency":1310,"frequencySweep":0,"frequencyDeltaSweep":0,"repeatFrequency":0,"frequencyJump1Onset":30,"frequencyJump1Amount":30,"frequencyJump2Onset":20,"frequencyJump2Amount":80,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"sine","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":35,"squareDutySweep":30,"flangerOffset":7,"flangerOffsetSweep":-3,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":2,"normalization":true,"amplification":20},
  ui_reject: {"_version":1,"_name":"pickup/coin","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.06,"sustainPunch":0,"decay":0.34,"tremoloDepth":0,"tremoloFrequency":10,"frequency":510,"frequencySweep":0,"frequencyDeltaSweep":0,"repeatFrequency":0,"frequencyJump1Onset":30,"frequencyJump1Amount":30,"frequencyJump2Onset":20,"frequencyJump2Amount":80,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"sine","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":35,"squareDutySweep":30,"flangerOffset":7,"flangerOffsetSweep":-3,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":0,"highPassCutoffSweep":0,"compression":2,"normalization":true,"amplification":20},
});

// Game-specific starting presets for the sound lab, listed after the jfxr ones.
export const CUSTOM_SOUND_PRESETS = Object.freeze({
  'horde/hitmarker': {"_version":1,"_name":"Unnamed","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.04,"sustainPunch":30,"decay":0.05,"tremoloDepth":100,"tremoloFrequency":24,"frequency":2800,"frequencySweep":-700,"frequencyDeltaSweep":-400,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":0,"harmonicsFalloff":0.5,"waveform":"square","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":50,"squareDutySweep":0,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":12,"bitCrushSweep":0,"lowPassCutoff":9000,"lowPassCutoffSweep":0,"highPassCutoff":1200,"highPassCutoffSweep":0,"compression":1.4,"normalization":true,"amplification":100},
  'horde/hitmarker soft': {"_version":1,"_name":"Unnamed","_locked":[],"sampleRate":44100,"attack":0,"sustain":0.035,"sustainPunch":50,"decay":0.045,"tremoloDepth":100,"tremoloFrequency":26,"frequency":3200,"frequencySweep":-1000,"frequencyDeltaSweep":0,"repeatFrequency":0,"frequencyJump1Onset":33,"frequencyJump1Amount":0,"frequencyJump2Onset":66,"frequencyJump2Amount":0,"harmonics":2,"harmonicsFalloff":0.4,"waveform":"sine","interpolateNoise":true,"vibratoDepth":0,"vibratoFrequency":10,"squareDuty":50,"squareDutySweep":0,"flangerOffset":0,"flangerOffsetSweep":0,"bitCrush":16,"bitCrushSweep":0,"lowPassCutoff":22050,"lowPassCutoffSweep":0,"highPassCutoff":1500,"highPassCutoffSweep":0,"compression":1.6,"normalization":true,"amplification":100}
});
